linters:
  enable:
    - errorlint
    - err113
    - exhaustruct
    - gocritic
    - gofmt
    - nilnil
    - nlreturn
    - revive
    - wrapcheck
    - wsl
  settings:
    wrapcheck:
      ignore-package-globs:
        - github.com/couchbaselabs/gocbconnstr
        - crypto/x509
      ignore-interface-regexps:
        - "analyticsRowReader"
        - "queryClient"
        - "clusterClient"
  exclusions:
    presets:
      - std-error-handling
version: "2"
